# NodeJS base image
FROM node:20

# Declaring env
ENV NODE_ENV development

# Working directory in the container
WORKDIR /BOB-ZPBackend

# Prepare for npm install
COPY package*.json ./

# Installing dependencies
RUN npm install

##### PM2 #####
# Installing pm2 globally
# RUN npm install pm2 -g

# Copy the rest
COPY . .

# Command to run the application
CMD ["sh", "-c", "node ./bin/www $DBURL"]

# Starting our application with PM2
# CMD pm2 start process.yml && tail -f /dev/null

# Exposing server port
EXPOSE 3001

# NodeJS Run Syntax: node ./bin/www [MongoDBURL]
# Example: node ./bin/www mongodb://127.0.0.1/ZP

# Build
# docker build -f Dockerfile -t bob_zpbackend:0.1 .

# Run
# docker run -d -p 3001:3001 -e DBURL="MongoDBAtlasURL" --name BOB_ZPBackend bob_zpbackend:0.1

##### PM2 process.yml file #####
# process.yml
# apps:
#    - script: "sh"
#      args: ["-c", "node ./bin/www $DBURL"]
#      name: "BOB-ZPBackend"
#      instances: 4
#      exec_mode: cluster
  