# Build Docker Image
# Publish Docker Image on Docker Hub
# Trigger Webhook on Azure Instance

name: CI/CD

on: # events
  push: # direct push trigger
    branches:
      - master
  pull_request: # "merge" trigger
    branches:
      - master
    types:
      - closed # only trigger when pull request is closed
  workflow_dispatch: # manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t cinoplayz/bob-zpbackend:latest .

      - name: Push to Docker Hub
        run: |
          docker push cinoplayz/bob-zpbackend:latest

  trigger-webhook:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Azure Instance
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://${{ secrets.AZURE_ADDRESS }}/hooks/redeploy-webhook'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "X-Webhook-Token": "${{ secrets.WEBHOOK_TOKEN }}"}'
          data: '{"image_name": "cinoplayz/bob-zpbackend:latest"}'
