name: Kotlin

on:
  push:
    branches: [dev]
    paths:
      - ".github/workflows/main.yml"
      - "**"
      - "test.sh"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ZPLanguage/

    steps:
      - uses: actions/checkout@v4

      - name: Install wdiff
        run: sudo apt-get install -y wdiff

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set Permission Gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew installdist

      - name: Set Permission test.sh and run.sh
        run: chmod +x ./test.sh ./run.sh

      - name: Test
        run: ./test.sh
